# Create Neuron Net of Hemming

Imports

In [385]:
import numpy as np
import pandas as pd

Class of MAXNET

In [386]:
class MaxNet:
    def __init__(self,
                 input_num: int,
                 epsilon: float = 1e-2,
                 max_iteration: int = 100000) -> None:
        self._weights = np.eye(input_num) * (1 + epsilon) - np.ones(
            (input_num, input_num)) * epsilon
        #         self._weights = np.full((input_num, input_num), epsilon)
        #         np.fill_diagonal(self._weights, 1)
        print(self._weights)
        self._max_iteration = max_iteration

    def predict(self, x_vector: np.ndarray) -> np.ndarray:
        y_vector = x_vector
        for i in range(self._max_iteration):
            y_vector = y_vector @ self._weights
            y_vector[y_vector < 0] = 0
            if np.shape(y_vector[y_vector > 0]) == (1, 1):
                break

        return y_vector

Class of Hemminng's NN

In [387]:
class HNN:
    def __init__(self, vector_massive: np.ndarray, epsilon=1e-2) -> None:
        self._weights = np.copy(vector_massive) / 2  # first layer
        self._maxnet = MaxNet(vector_massive.shape[1], epsilon)  # second layer

    def predict(self, vector_to_check: np.ndarray) -> np.ndarray:
        result = vector_to_check @ self._weights
        result[result < 0] = 0
        result = self._maxnet.predict(result)
        return result

# Example

### Generate Data.
Ya, that's cringe

In [388]:
x_1 = np.array([
    -1, -1, 1, -1, -1, -1, 1, 1, -1, -1, 1, -1, 1, -1, -1, -1, -1, 1, -1, -1,
    -1, -1, 1, -1, -1
])

x_2 = np.array([
    -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1,
    -1, 1, 1, 1, -1
])

x_3 = np.array([
    -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1,
    1, 1, 1, -1
])

x_4 = np.array([
    -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1,
    -1, -1, 1, -1
])

x_5 = np.array([
    -1, 1, 1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1,
    1, 1, 1, -1
])

x_6 = np.array([
    -1, 1, 1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1,
    1, 1, 1, -1
])

x_7 = np.array([
    -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, -1, -1,
    -1, -1, 1, -1, -1
])

x_8 = np.array([
    -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1,
    1, 1, 1, -1
])

x_9 = np.array([
    -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1,
    1, 1, 1, -1
])

x_0 = np.array([
    -1, 1, 1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1, 1, -1, 1, -1, -1,
    1, 1, 1, -1
])

In [389]:
weights = np.array([x_0, x_1, x_2, x_3, x_4, x_5, x_6, x_7, x_8,
                    x_9]).transpose()

### Create HNN

In [390]:
model = HNN(weights)

[[ 1.   -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01]
 [-0.01  1.   -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01]
 [-0.01 -0.01  1.   -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01]
 [-0.01 -0.01 -0.01  1.   -0.01 -0.01 -0.01 -0.01 -0.01 -0.01]
 [-0.01 -0.01 -0.01 -0.01  1.   -0.01 -0.01 -0.01 -0.01 -0.01]
 [-0.01 -0.01 -0.01 -0.01 -0.01  1.   -0.01 -0.01 -0.01 -0.01]
 [-0.01 -0.01 -0.01 -0.01 -0.01 -0.01  1.   -0.01 -0.01 -0.01]
 [-0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01  1.   -0.01 -0.01]
 [-0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01  1.   -0.01]
 [-0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01 -0.01  1.  ]]


### Check HNN

In [391]:
model.predict(x_0)

array([2.96739926, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])