In [64]:
import numpy as np
from typing import *

In [125]:
class Neuron:
    def __init__(self, bias: float, activ_func: Callable[[float],
                                                         float]) -> None:

        self._bias = bias
        self._activ_func = activ_func
        self._state = 0.0
        self._new_state = 0.0

    def run_forward(self, weights: np.ndarray, inputs: np.ndarray) -> float:
        print(weights)
        print(inputs)
        results = (weights * inputs).sum() - self._bias
        self._new_state = self._activ_func(results)
        return self._new_state

    def update(self):
        self._state = self._new_state

In [132]:
class RNN:
    def __init__(self, output_neuron_number: int, input_count: int) -> None:
        self._input_count = input_count
        self._output_neuron_number = output_neuron_number
        self._weights_matrix = []
        self._input_weights = []
        self._neurons = []

    def add(self, input_weight_i: float, bias: float, activ_func: Callable[[float],
                                                                           float]) -> None:
        self._neurons.append(Neuron(bias, activ_func))
        self._input_weights.append(input_weight_i)
        self._weights_matrix.append([0] * (len(self._neurons) - 1))
        for weights in self._weights_matrix:
            weights.append(0)

    def set_weight(self, weight_num: int, neuron_num: int, weight: float) -> None:
        self._weights_matrix[neuron_num][weight_num] = weight

    def run_forward(self, x_input: np.ndarray, sync=True) -> float:
        state = [neuron._state for neuron in self._neurons]

        for i in range(len(self._neurons)):
            self._neurons[i].run_forward(
                self._weights_matrix[i], self._input_weights[i])

            if not sync:
                self._neurons[i].update()

        if sync:
            for neuron in self._neurons:
                neuron.update()
        return self._neurons[self._output_neuron_number]._state

# Task 1

Program RNN, with:
1) divergence
2) period
3) convergence
4) cycle

In [133]:
def run_nn(activ_function: Callable[[float], float]) -> List[float]:
    nn = RNN(3, 2)
    nn.add([1,5,-2], -1, activ_function)
    nn.add([-1,-4,0], 2, activ_function)
    nn.add([4,0,3], 0, activ_function)
    nn.add([-2,1,1], 1, activ_function)

    nn.set_weight(0,1, 3)
    nn.set_weight(0,3, 1)
    nn.set_weight(1,2, -2)
    nn.set_weight(1,3, 2)
    nn.set_weight(2,0, 4)
    nn.set_weight(3,1, 1)
    nn.set_weight(3,2, -1)
            
    inputs = [
            [0,0,1],
            [1,2,0],
            [-1,-4,-1],
            [4,1,2]
            ]
    outputs = [nn.run_forward(i) for i in inputs]

        
    return outputs

In [134]:
# 1
# exp
run_nn(np.exp)

[0, 0, 4, 0]
[1, 5, -2]


TypeError: can't multiply sequence by non-int of type 'list'

In [95]:
# 2
# sinus
run_nn(np.sin)

[array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428]),
 array([-0.99739428])]

In [56]:
# 3
# 1/n^2

In [114]:
n = np.array([1, 2, 3])
type(n)

numpy.ndarray